-- AlterTable
ALTER TABLE "Order" ADD COLUMN "customerDoc" TEXT;

-- AlterTable
ALTER TABLE "Store" ADD COLUMN "deliveryFeePuerto" DOUBLE PRECISION NOT NULL DEFAULT 2500,
ADD COLUMN "deliveryFeePradomar" DOUBLE PRECISION NOT NULL DEFAULT 3000,
ADD COLUMN "deliveryFeeSalgar" DOUBLE PRECISION NOT NULL DEFAULT 5000,
ADD COLUMN "deliveryFeeBarranquilla" DOUBLE PRECISION NOT NULL DEFAULT 8000;
